version: "3.5"
services:

  nginx:
    container_name: "tdd_api_nginx"
    image: nginx:1.15
    depends_on:
      - php
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/cors_response.inc:/etc/nginx/conf.d/cors_response.inc

  php:
    container_name: "tdd_api_php"
    build: ./docker/php
    volumes:
      - .:/var/www/
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ~/.composer-docker:/root/.composer
      - ~/.bash_history:/root/.bash_history
